### get professores
GET http://localhost:3000/professores HTTP/1.1
Content-Type: application/json

### get professor
GET http://localhost:3000/professores/1 HTTP/1.1
Content-Type: application/json

### inserir professor
POST http://localhost:3000/professores HTTP/1.1
Content-Type: application/json

{
     "nome": "Aujor Andrade",
     "email": "prof.aujor@email.com",
     "sala": "3C",
     "turno": "Noite",
     "disciplina": "Governança de TI"
}

### alterar professor
PUT http://localhost:3000/professores/2 HTTP/1.1
Content-Type: application/json

{
     "nome": "Joice Mota",
     "email": "prof.joice@email.com",
     "sala": "1A",
     "turno": "Tarde",
     "disciplina": "Banco de Dados Geográficos"
}

### excluir professor
DELETE http://localhost:3000/professores/5 HTTP/1.1


### get cursos
GET http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

### get curso
GET http://localhost:3000/cursos/2 HTTP/1.1
Content-Type: application/json

### inserir curso
POST http://localhost:3000/cursos HTTP/1.1
Content-Type: application/json

{
     "nome": "Bacharelado em Sistemas para Internet",
     "sigla": "BSI",
     "descricao": "Curso de Bacharelado do Instituto Federal Catarinense",
     "cordenador": "Aujor Andrade"
}

### alterar curso
PUT http://localhost:3000/cursos/2 HTTP/1.1
Content-Type: application/json

{
    "nome": "Bacharelado em Sistemas para Internet",
     "sigla": "BSI",
     "descricao": "Curso de Bacharelado do Instituto Federal Catarinense",
     "cordenador": "Aujor Andrade"
}

### excluir curso
DELETE http://localhost:3000/cursos/2 HTTP/1.1
